### PR TITLE
Variable modifications

### PR DESCRIPTION
**Pull request by cs-joao-souza**
Change currentCenterCell to open var;
Change currentCenterCellIndex to open var;

### CODE REVIEW

**Comment by superpeteblaze** [comment]
@cs-joao-souza - I am thinking about this a bit more. The reason you want them `open` is because you want to mock them?

**Comment by cs-joao-souza** [comment]
@superpeteblaze  To stub methods in unit testing in Swift, if you don't have a protocol that define that functionality so you need to override it and fake your method call. The reason to do that, is that i don't want to test your class, because i know that it works so i just want to verify if your method is called, or just stub some methods.

**Comment by superpeteblaze** [comment]
@cs-joao-souza Yes, I understand that a protocol would be needed to stub, and it would be preferable to overriding. I don't think it really makes sense to change the access level of these properties, so I suggest another idea:

* How about you create a protocol in your codebase, and in that protocol, you declare two properties with the same signature as `currentCenterCell` and `currentCenterCellIndex`. The protocol you create can contain whatever ScalingCarouselView properties/methods you want to stub. You could then create an extension on ScalingCarouselView to conform to this protocol, and this would enable you to stub it.

The reason I say do this locally in your codebase, is that it doesn't really make sense for ScalingCarousel to be based off a protocol.

**Comment by cs-joao-souza** [comment]
@superpeteblaze There is a rule haha. If you want to test more, just let your variables public or open. Im kidding, just a joke. But talking seriously imagine if i need to do this for every class that has a function that i need to stub? My project will become a bag of protocols with no sense, because it won't be reused, so it is a protocol with no sense. What i'm thinking is about the open closed principle. Classes should be opened for extension but closed for modifications. If theses variables keep being only public, you won't let me inherit your class, i do need to create a new one. Furthermore, theses variables is just a get i can't even set any variable to this. What you think?

**Comment by superpeteblaze** [comment]
Yes, the open closed principle is valid, and correct. However, the rule is not intended to mean that types should always be open for extension.

I agree on the protocol approach, it's not feasible.

But looking at it again, as the entire class is `open`, perhaps it's not a problem to make these two properties `open` also.

Also, yes, if you want to make them `get` only, that would be fine.

**Comment by cs-joao-souza** [comment]
So, what is your answer? ;)

**Comment by superpeteblaze** [comment]
As I said above, keeping them open is fine, and if you want to update them to be `get` only, then awesome

**Comment by cs-joao-souza** [comment]
These variables are already get only haha. So are you going to accept my PR?

**Comment by superpeteblaze** [comment]
Ah yes, I forget they were computed properties. Sure, I will accept it

**Comment by cs-joao-souza** [comment]
Thanks. And don't forget to update the Pods. =D

**Comment by superpeteblaze** [comment]
Done.

**Pull request merged**
